apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: pvc-dc1-wordpress-app
   annotations:
    hitachi.io/note: "pvc-dc1-wordpress-app"
spec:
   accessModes:
   - ReadWriteOnce
   resources:
      requests:
         storage: 20Gi
   storageClassName: sc-gold-dc1   
